/**
 * Block registry — every component the editor can place, with its default
 * content, the fields shown in the inspector, and which style controls apply.
 * Rendering lives in BlockRender.tsx (keyed by `type`).
 */
import { type BlockDef, type Block, type BlockStyle, uid, clone } from './types'

const allStyle = {
  typography: true,
  colors: true,
  spacing: true,
  border: true,
  layout: true,
}

export const BLOCKS: BlockDef[] = [
  // ─────────────────────────── Layout ───────────────────────────
  {
    type: 'section',
    label: 'Section',
    category: 'Layout',
    icon: 'Square',
    description: 'Bande pleine largeur — déposez des blocs à l’intérieur.',
    isContainer: true,
    defaultProps: {},
    defaultStyle: { paddingY: 64, paddingX: 24, maxWidth: 1200 },
    fields: [],
    style: allStyle,
  },
  {
    type: 'columns',
    label: 'Colonnes',
    category: 'Layout',
    icon: 'Columns3',
    description: 'Disposition en 2 à 4 colonnes.',
    isContainer: true,
    defaultProps: { columns: 2, gap: 24, stackOnMobile: true },
    defaultStyle: { paddingY: 24 },
    fields: [
      {
        key: 'columns',
        label: 'Nombre de colonnes',
        type: 'select',
        options: [
          { label: '1', value: '1' },
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      { key: 'gap', label: 'Espacement (px)', type: 'number' },
      { key: 'stackOnMobile', label: 'Empiler sur mobile', type: 'toggle' },
    ],
    style: { spacing: true, colors: true },
  },
  {
    type: 'card',
    label: 'Carte',
    category: 'Layout',
    icon: 'CreditCard',
    description: 'Conteneur en verre arrondi.',
    isContainer: true,
    defaultProps: {},
    defaultStyle: { paddingY: 28, paddingX: 28 },
    fields: [],
    style: allStyle,
  },
  {
    type: 'spacer',
    label: 'Espace',
    category: 'Layout',
    icon: 'MoveVertical',
    defaultProps: { height: 48 },
    fields: [{ key: 'height', label: 'Hauteur (px)', type: 'number' }],
    style: {},
  },
  {
    type: 'divider',
    label: 'Séparateur',
    category: 'Layout',
    icon: 'Minus',
    defaultProps: {},
    defaultStyle: { marginTop: 16, marginBottom: 16 },
    fields: [],
    style: { spacing: true, colors: true },
  },

  // ─────────────────────────── Texte ───────────────────────────
  {
    type: 'eyebrow',
    label: 'Sur-titre (kicker)',
    category: 'Texte',
    icon: 'Tag',
    defaultProps: { text: 'D-Tech Algérie' },
    defaultStyle: {},
    fields: [{ key: 'text', label: 'Texte', type: 'text' }],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'heading',
    label: 'Titre',
    category: 'Texte',
    icon: 'Heading',
    defaultProps: { text: 'Un titre qui accroche', level: 'h2' },
    defaultStyle: { fontSize: 40, fontWeight: 800 },
    fields: [
      { key: 'text', label: 'Texte', type: 'text' },
      {
        key: 'level',
        label: 'Niveau',
        type: 'select',
        options: [
          { label: 'H1', value: 'h1' },
          { label: 'H2', value: 'h2' },
          { label: 'H3', value: 'h3' },
          { label: 'H4', value: 'h4' },
        ],
      },
    ],
    style: allStyle,
  },
  {
    type: 'paragraph',
    label: 'Paragraphe',
    category: 'Texte',
    icon: 'Pilcrow',
    defaultProps: {
      text: 'Décrivez votre offre en quelques phrases claires. Cliquez pour modifier ce texte directement sur la page.',
    },
    defaultStyle: { fontSize: 16, lineHeight: 1.65 },
    fields: [{ key: 'text', label: 'Texte', type: 'textarea' }],
    style: allStyle,
  },
  {
    type: 'list',
    label: 'Liste',
    category: 'Texte',
    icon: 'List',
    defaultProps: {
      ordered: false,
      items: [
        { text: 'Premier point clé' },
        { text: 'Deuxième avantage' },
        { text: 'Troisième élément' },
      ],
    },
    fields: [
      { key: 'ordered', label: 'Liste numérotée', type: 'toggle' },
      {
        key: 'items',
        label: 'Éléments',
        type: 'list',
        addLabel: 'Ajouter un élément',
        itemFields: [{ key: 'text', label: 'Texte', type: 'text' }],
      },
    ],
    style: allStyle,
  },
  {
    type: 'quote',
    label: 'Citation',
    category: 'Texte',
    icon: 'Quote',
    defaultProps: {
      text: 'Un service impeccable et des produits au top. Je recommande D-Tech sans hésiter.',
      author: 'Client satisfait',
    },
    defaultStyle: { fontSize: 22, italic: true },
    fields: [
      { key: 'text', label: 'Citation', type: 'textarea' },
      { key: 'author', label: 'Auteur', type: 'text' },
    ],
    style: allStyle,
  },
  {
    type: 'button',
    label: 'Bouton',
    category: 'Texte',
    icon: 'MousePointerClick',
    defaultProps: {
      label: 'Découvrir',
      href: '#',
      variant: 'primary',
      newTab: false,
    },
    fields: [
      { key: 'label', label: 'Libellé', type: 'text' },
      { key: 'href', label: 'Lien', type: 'text', placeholder: '/products' },
      {
        key: 'variant',
        label: 'Style',
        type: 'select',
        options: [
          { label: 'Plein (mint)', value: 'primary' },
          { label: 'Contour', value: 'ghost' },
          { label: 'Lien', value: 'link' },
        ],
      },
      { key: 'newTab', label: 'Ouvrir dans un nouvel onglet', type: 'toggle' },
    ],
    style: { spacing: true, layout: true, typography: true },
  },

  // ─────────────────────────── Médias ───────────────────────────
  {
    type: 'image',
    label: 'Image',
    category: 'Médias',
    icon: 'Image',
    defaultProps: {
      src: '/placeholder-product.png',
      alt: 'Image',
      fit: 'cover',
      ratio: '16/9',
    },
    defaultStyle: { radius: 14 },
    fields: [
      { key: 'src', label: 'URL de l’image', type: 'image' },
      { key: 'alt', label: 'Texte alternatif', type: 'text' },
      {
        key: 'fit',
        label: 'Ajustement',
        type: 'select',
        options: [
          { label: 'Couvrir', value: 'cover' },
          { label: 'Contenir', value: 'contain' },
        ],
      },
      {
        key: 'ratio',
        label: 'Ratio',
        type: 'select',
        options: [
          { label: '16 / 9', value: '16/9' },
          { label: '4 / 3', value: '4/3' },
          { label: '1 / 1', value: '1/1' },
          { label: '3 / 4', value: '3/4' },
          { label: 'Auto', value: 'auto' },
        ],
      },
    ],
    style: { spacing: true, border: true, layout: true },
  },
  {
    type: 'gallery',
    label: 'Galerie',
    category: 'Médias',
    icon: 'Images',
    defaultProps: {
      columns: 3,
      gap: 12,
      items: [
        { src: '/placeholder-product.png', alt: '' },
        { src: '/placeholder-product.png', alt: '' },
        { src: '/placeholder-product.png', alt: '' },
      ],
    },
    fields: [
      {
        key: 'columns',
        label: 'Colonnes',
        type: 'select',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      { key: 'gap', label: 'Espacement (px)', type: 'number' },
      {
        key: 'items',
        label: 'Images',
        type: 'list',
        addLabel: 'Ajouter une image',
        itemFields: [
          { key: 'src', label: 'URL', type: 'image' },
          { key: 'alt', label: 'Alt', type: 'text' },
        ],
      },
    ],
    style: { spacing: true },
  },
  {
    type: 'video',
    label: 'Vidéo',
    category: 'Médias',
    icon: 'Video',
    defaultProps: { url: '', ratio: '16/9' },
    defaultStyle: { radius: 14 },
    fields: [
      {
        key: 'url',
        label: 'Lien YouTube / Vimeo / MP4',
        type: 'text',
        placeholder: 'https://www.youtube.com/watch?v=…',
      },
    ],
    style: { spacing: true, border: true, layout: true },
  },
  {
    type: 'icon',
    label: 'Icône',
    category: 'Médias',
    icon: 'Sparkles',
    defaultProps: { name: 'Sparkles', size: 40 },
    defaultStyle: {},
    fields: [
      {
        key: 'name',
        label: 'Icône',
        type: 'select',
        options: [
          'Sparkles', 'Zap', 'ShieldCheck', 'Truck', 'Headphones', 'Cpu',
          'Monitor', 'Wifi', 'Star', 'Heart', 'Award', 'Rocket', 'Check',
          'Phone', 'Mail', 'MapPin', 'Clock', 'Gift', 'Tag', 'Package',
        ].map((v) => ({ label: v, value: v })),
      },
      { key: 'size', label: 'Taille (px)', type: 'number' },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'logoCloud',
    label: 'Bandeau de logos',
    category: 'Médias',
    icon: 'Boxes',
    defaultProps: {
      title: 'Nos marques partenaires',
      items: [
        { text: 'ASUS' }, { text: 'HP' }, { text: 'TP-Link' },
        { text: 'Epson' }, { text: 'GameMax' }, { text: 'Logitech' },
      ],
    },
    fields: [
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Marques',
        type: 'list',
        addLabel: 'Ajouter une marque',
        itemFields: [{ key: 'text', label: 'Nom', type: 'text' }],
      },
    ],
    style: { colors: true, spacing: true },
  },

  // ────────────────────────── Sections ──────────────────────────
  {
    type: 'navbar',
    label: 'Barre de navigation',
    category: 'Sections',
    icon: 'PanelTop',
    defaultProps: {
      brand: 'D-Tech',
      links: [
        { label: 'Produits', href: '/products' },
        { label: 'Catégories', href: '/categories' },
        { label: 'Marques', href: '/brands' },
        { label: 'À propos', href: '/about' },
      ],
      cta: 'Contact',
      ctaHref: '/inquiry',
    },
    defaultStyle: { paddingY: 18, paddingX: 28 },
    fields: [
      { key: 'brand', label: 'Marque', type: 'text' },
      {
        key: 'links',
        label: 'Liens',
        type: 'list',
        addLabel: 'Ajouter un lien',
        itemFields: [
          { key: 'label', label: 'Libellé', type: 'text' },
          { key: 'href', label: 'Lien', type: 'text' },
        ],
      },
      { key: 'cta', label: 'Bouton', type: 'text' },
      { key: 'ctaHref', label: 'Lien du bouton', type: 'text' },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'hero',
    label: 'Hero (vedette)',
    category: 'Sections',
    icon: 'Megaphone',
    description: 'Section d’accueil — sur-titre, titre, sous-titre, boutons, stats.',
    defaultProps: {
      kicker: 'Showroom informatique · Alger',
      title: 'Le matériel tech, livré avec style.',
      accent: 'avec style.',
      subtitle:
        '393 produits, 21 marques. Composants, périphériques et solutions pro — sélectionnés, testés, en stock.',
      primaryLabel: 'Voir le catalogue',
      primaryHref: '/products',
      secondaryLabel: 'Nous contacter',
      secondaryHref: '/inquiry',
      stats: [
        { value: '393', label: 'Produits' },
        { value: '21', label: 'Marques' },
        { value: '20', label: 'Catégories' },
      ],
    },
    defaultStyle: { paddingY: 96, paddingX: 24, textAlign: 'left' },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'textarea' },
      { key: 'accent', label: 'Partie en mint (doit figurer dans le titre)', type: 'text' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton principal', type: 'text' },
      { key: 'primaryHref', label: 'Lien principal', type: 'text' },
      { key: 'secondaryLabel', label: 'Bouton secondaire', type: 'text' },
      { key: 'secondaryHref', label: 'Lien secondaire', type: 'text' },
      {
        key: 'stats',
        label: 'Statistiques',
        type: 'list',
        addLabel: 'Ajouter une stat',
        itemFields: [
          { key: 'value', label: 'Valeur', type: 'text' },
          { key: 'label', label: 'Libellé', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'heroSimple',
    label: 'Hero centré',
    category: 'Sections',
    icon: 'AlignCenter',
    defaultProps: {
      kicker: 'Nouveau',
      title: 'Une accroche simple et centrée',
      subtitle: 'Idéale pour une page de campagne ou une landing page.',
      primaryLabel: 'Commencer',
      primaryHref: '#',
    },
    defaultStyle: { paddingY: 100, paddingX: 24, textAlign: 'center' },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'textarea' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton', type: 'text' },
      { key: 'primaryHref', label: 'Lien', type: 'text' },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'featureGrid',
    label: 'Grille d’atouts',
    category: 'Sections',
    icon: 'LayoutGrid',
    defaultProps: {
      kicker: 'Pourquoi D-Tech',
      title: 'Tout pour bien s’équiper',
      columns: 3,
      items: [
        { icon: 'Truck', title: 'Livraison rapide', text: 'Partout en Algérie, emballage soigné.' },
        { icon: 'ShieldCheck', title: 'Garantie', text: 'Produits authentiques et garantis.' },
        { icon: 'Headphones', title: 'Conseil', text: 'Une équipe qui connaît le matériel.' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'columns',
        label: 'Colonnes',
        type: 'select',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      {
        key: 'items',
        label: 'Atouts',
        type: 'list',
        addLabel: 'Ajouter un atout',
        itemFields: [
          { key: 'icon', label: 'Icône', type: 'text' },
          { key: 'title', label: 'Titre', type: 'text' },
          { key: 'text', label: 'Texte', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'statsBand',
    label: 'Bandeau de chiffres',
    category: 'Sections',
    icon: 'BarChart3',
    defaultProps: {
      items: [
        { value: '393', label: 'Produits en stock' },
        { value: '21', label: 'Marques' },
        { value: '20', label: 'Catégories' },
        { value: '100%', label: 'Authentiques' },
      ],
    },
    defaultStyle: { paddingY: 56, paddingX: 24 },
    fields: [
      {
        key: 'items',
        label: 'Chiffres',
        type: 'list',
        addLabel: 'Ajouter un chiffre',
        itemFields: [
          { key: 'value', label: 'Valeur', type: 'text' },
          { key: 'label', label: 'Libellé', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'stat',
    label: 'Statistique',
    category: 'Texte',
    icon: 'TrendingUp',
    defaultProps: { value: '393', label: 'Produits' },
    defaultStyle: { textAlign: 'center' },
    fields: [
      { key: 'value', label: 'Valeur', type: 'text' },
      { key: 'label', label: 'Libellé', type: 'text' },
    ],
    style: allStyle,
  },
  {
    type: 'ctaBanner',
    label: 'Bannière d’appel à l’action',
    category: 'Sections',
    icon: 'Flag',
    defaultProps: {
      title: 'Prêt à passer commande ?',
      subtitle: 'Contactez-nous sur WhatsApp, on s’occupe du reste.',
      primaryLabel: 'Commander via WhatsApp',
      primaryHref: 'https://wa.me/213560990506',
    },
    defaultStyle: { paddingY: 64, paddingX: 40, textAlign: 'center' },
    fields: [
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton', type: 'text' },
      { key: 'primaryHref', label: 'Lien', type: 'text' },
    ],
    style: allStyle,
  },
  {
    type: 'testimonials',
    label: 'Témoignages',
    category: 'Sections',
    icon: 'MessageSquareQuote',
    defaultProps: {
      kicker: 'Avis clients',
      title: 'Ils nous font confiance',
      items: [
        { text: 'Commande reçue en 24h, produit nickel.', author: 'Amine', role: 'Alger' },
        { text: 'Bon conseil pour mon PC gamer, top.', author: 'Yacine', role: 'Oran' },
        { text: 'Prix corrects et service sérieux.', author: 'Sofia', role: 'Constantine' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Témoignages',
        type: 'list',
        addLabel: 'Ajouter un témoignage',
        itemFields: [
          { key: 'text', label: 'Texte', type: 'textarea' },
          { key: 'author', label: 'Auteur', type: 'text' },
          { key: 'role', label: 'Rôle / ville', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'faq',
    label: 'FAQ (accordéon)',
    category: 'Sections',
    icon: 'CircleHelp',
    defaultProps: {
      kicker: 'Questions',
      title: 'Questions fréquentes',
      items: [
        { q: 'Livrez-vous partout en Algérie ?', a: 'Oui, dans les 58 wilayas via nos partenaires de livraison.' },
        { q: 'Quels moyens de paiement ?', a: 'Paiement à la livraison ou en showroom.' },
        { q: 'Les produits sont-ils garantis ?', a: 'Tous nos produits sont authentiques et garantis.' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24, maxWidth: 820 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Questions',
        type: 'list',
        addLabel: 'Ajouter une question',
        itemFields: [
          { key: 'q', label: 'Question', type: 'text' },
          { key: 'a', label: 'Réponse', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'pricing',
    label: 'Tarifs',
    category: 'Sections',
    icon: 'BadgeDollarSign',
    defaultProps: {
      kicker: 'Offres',
      title: 'Nos formules de montage PC',
      items: [
        { name: 'Essentiel', price: '45 000 DA', features: 'Montage · Test · Garantie', featured: false, cta: 'Choisir' },
        { name: 'Performance', price: '95 000 DA', features: 'Montage premium · Câblage · OC léger', featured: true, cta: 'Choisir' },
        { name: 'Extrême', price: '180 000 DA', features: 'Watercooling · Benchmarks · Support', featured: false, cta: 'Choisir' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Formules',
        type: 'list',
        addLabel: 'Ajouter une formule',
        itemFields: [
          { key: 'name', label: 'Nom', type: 'text' },
          { key: 'price', label: 'Prix', type: 'text' },
          { key: 'features', label: 'Inclus (séparés par ·)', type: 'textarea' },
          { key: 'cta', label: 'Bouton', type: 'text' },
          { key: 'featured', label: 'Mise en avant', type: 'toggle' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'newsletter',
    label: 'Newsletter',
    category: 'Sections',
    icon: 'MailPlus',
    defaultProps: {
      title: 'Restez informé',
      subtitle: 'Nouveautés, promos et arrivages — sans spam.',
      placeholder: 'Votre e-mail',
      button: 'S’inscrire',
    },
    defaultStyle: { paddingY: 64, paddingX: 24, textAlign: 'center' },
    fields: [
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'placeholder', label: 'Placeholder', type: 'text' },
      { key: 'button', label: 'Bouton', type: 'text' },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'contactBand',
    label: 'Bandeau contact',
    category: 'Sections',
    icon: 'PhoneCall',
    defaultProps: {
      title: 'Parlons de votre projet',
      phone: '0560 99 05 06',
      whatsapp: 'https://wa.me/213560990506',
      address: 'Alger, Algérie',
    },
    defaultStyle: { paddingY: 64, paddingX: 24 },
    fields: [
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'phone', label: 'Téléphone', type: 'text' },
      { key: 'whatsapp', label: 'Lien WhatsApp', type: 'text' },
      { key: 'address', label: 'Adresse', type: 'text' },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'imageText',
    label: 'Image + texte',
    category: 'Sections',
    icon: 'PanelLeft',
    defaultProps: {
      kicker: 'À propos',
      title: 'Une équipe passionnée de tech',
      text: 'Depuis Alger, nous sélectionnons le meilleur matériel pour les particuliers et les pros. Conseil, montage, service après-vente.',
      image: '/placeholder-product.png',
      side: 'right',
      buttonLabel: 'En savoir plus',
      buttonHref: '/about',
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'text', label: 'Texte', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'side',
        label: 'Position de l’image',
        type: 'select',
        options: [
          { label: 'Droite', value: 'right' },
          { label: 'Gauche', value: 'left' },
        ],
      },
      { key: 'buttonLabel', label: 'Bouton', type: 'text' },
      { key: 'buttonHref', label: 'Lien', type: 'text' },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'footer',
    label: 'Pied de page',
    category: 'Sections',
    icon: 'PanelBottom',
    defaultProps: {
      brand: 'D-Tech',
      tagline: 'Showroom informatique — Alger, Algérie.',
      columns: [
        { title: 'Boutique', links: 'Produits|/products,Catégories|/categories,Marques|/brands' },
        { title: 'Entreprise', links: 'À propos|/about,Contact|/inquiry,Mentions|/legal' },
      ],
      copyright: '© 2026 D-Tech Algérie. Tous droits réservés.',
    },
    defaultStyle: { paddingY: 56, paddingX: 28 },
    fields: [
      { key: 'brand', label: 'Marque', type: 'text' },
      { key: 'tagline', label: 'Accroche', type: 'textarea' },
      {
        key: 'columns',
        label: 'Colonnes de liens',
        type: 'list',
        addLabel: 'Ajouter une colonne',
        itemFields: [
          { key: 'title', label: 'Titre', type: 'text' },
          { key: 'links', label: 'Liens (Libellé|/url séparés par ,)', type: 'textarea' },
        ],
      },
      { key: 'copyright', label: 'Mention de bas de page', type: 'text' },
    ],
    style: { colors: true, spacing: true },
  },

  // ────────────────────────── Commerce ──────────────────────────
  {
    type: 'productGrid',
    label: 'Grille de produits',
    category: 'Commerce',
    icon: 'ShoppingBag',
    defaultProps: {
      kicker: 'Catalogue',
      title: 'Sélection du moment',
      columns: 4,
      items: [
        { name: 'Carte graphique RTX', brand: 'ASUS', price: '180 000 DA', rating: '4.8', image: '/placeholder-product.png' },
        { name: 'Écran 27" 165Hz', brand: 'HP', price: '52 000 DA', rating: '4.6', image: '/placeholder-product.png' },
        { name: 'Routeur Wi-Fi 6', brand: 'TP-Link', price: '14 500 DA', rating: '4.7', image: '/placeholder-product.png' },
        { name: 'Imprimante laser', brand: 'Epson', price: '38 000 DA', rating: '4.5', image: '/placeholder-product.png' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'columns',
        label: 'Colonnes',
        type: 'select',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      {
        key: 'items',
        label: 'Produits',
        type: 'list',
        addLabel: 'Ajouter un produit',
        itemFields: [
          { key: 'image', label: 'Image', type: 'image' },
          { key: 'name', label: 'Nom', type: 'text' },
          { key: 'brand', label: 'Marque', type: 'text' },
          { key: 'price', label: 'Prix', type: 'text' },
          { key: 'rating', label: 'Note', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'categoryRail',
    label: 'Rail de catégories',
    category: 'Commerce',
    icon: 'FolderKanban',
    defaultProps: {
      kicker: 'Catégories',
      title: 'Explorer par famille',
      items: [
        { name: 'Composants', count: '120' },
        { name: 'Périphériques', count: '86' },
        { name: 'Réseau', count: '49' },
        { name: 'Impression', count: '40' },
        { name: 'Gaming', count: '33' },
      ],
    },
    defaultStyle: { paddingY: 64, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Catégories',
        type: 'list',
        addLabel: 'Ajouter une catégorie',
        itemFields: [
          { key: 'name', label: 'Nom', type: 'text' },
          { key: 'count', label: 'Nombre de produits', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'brandRail',
    label: 'Rail de marques',
    category: 'Commerce',
    icon: 'Tags',
    defaultProps: {
      kicker: 'Marques',
      title: 'Nos partenaires',
      items: [
        { name: 'ASUS' }, { name: 'HP' }, { name: 'TP-Link' },
        { name: 'Epson' }, { name: 'GameMax' }, { name: 'Ink Master' },
        { name: 'Logitech' }, { name: 'MSI' },
      ],
    },
    defaultStyle: { paddingY: 56, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Marques',
        type: 'list',
        addLabel: 'Ajouter une marque',
        itemFields: [{ key: 'name', label: 'Nom', type: 'text' }],
      },
    ],
    style: { colors: true, spacing: true },
  },

  // ──────────────────────── Sections (v2) ────────────────────────
  {
    type: 'heroImage',
    label: 'Hero · image en fond',
    category: 'Sections',
    icon: 'Image',
    description: 'Hero avec une image en arrière-plan plein-cadre.',
    defaultProps: {
      kicker: 'Nouvelle collection',
      title: 'L’univers pro à portée de main.',
      subtitle:
        'Découvrez notre sélection 2026 — testée, garantie, livrée partout en Algérie.',
      primaryLabel: 'Voir le catalogue',
      primaryHref: '/products',
      secondaryLabel: 'En savoir plus',
      secondaryHref: '/about',
      image:
        'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600',
      overlay: 55,
    },
    defaultStyle: { paddingY: 120, paddingX: 32, textAlign: 'left' },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'textarea' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton principal', type: 'text' },
      { key: 'primaryHref', label: 'Lien principal', type: 'text' },
      { key: 'secondaryLabel', label: 'Bouton secondaire', type: 'text' },
      { key: 'secondaryHref', label: 'Lien secondaire', type: 'text' },
      { key: 'image', label: 'Image de fond', type: 'image' },
      { key: 'overlay', label: 'Voile sombre (0-100%)', type: 'number' },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'heroVideo',
    label: 'Hero · vidéo en fond',
    category: 'Sections',
    icon: 'PlayCircle',
    description: 'Hero avec une vidéo (YouTube/Vimeo/MP4) en arrière-plan.',
    defaultProps: {
      kicker: 'En direct du showroom',
      title: 'Le matériel pro, en mouvement.',
      subtitle: 'Une boucle vidéo en fond pour donner de l’énergie à la page.',
      primaryLabel: 'Voir le catalogue',
      primaryHref: '/products',
      videoUrl: '',
      overlay: 60,
    },
    defaultStyle: { paddingY: 140, paddingX: 32, textAlign: 'center' },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'textarea' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton', type: 'text' },
      { key: 'primaryHref', label: 'Lien', type: 'text' },
      {
        key: 'videoUrl',
        label: 'URL vidéo (YouTube / Vimeo / .mp4)',
        type: 'text',
        placeholder: 'https://...',
      },
      { key: 'overlay', label: 'Voile sombre (0-100%)', type: 'number' },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'heroSplit',
    label: 'Hero · split (texte + visuel)',
    category: 'Sections',
    icon: 'Columns2',
    description: 'Deux colonnes : copy à gauche, image à droite (ou inverse).',
    defaultProps: {
      kicker: 'Nouveau',
      title: 'Le matériel tech, livré avec style.',
      subtitle:
        'Composants, périphériques et solutions pro — sélectionnés, testés, en stock.',
      primaryLabel: 'Voir le catalogue',
      primaryHref: '/products',
      image: '/placeholder-product.png',
      side: 'right',
    },
    defaultStyle: { paddingY: 96, paddingX: 32 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'textarea' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      { key: 'primaryLabel', label: 'Bouton', type: 'text' },
      { key: 'primaryHref', label: 'Lien', type: 'text' },
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'side',
        label: 'Position de l’image',
        type: 'select',
        options: [
          { label: 'Droite', value: 'right' },
          { label: 'Gauche', value: 'left' },
        ],
      },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'sectionHeader',
    label: 'En-tête de section',
    category: 'Sections',
    icon: 'Type',
    description: 'Sur-titre + titre + sous-titre combinés — pour introduire une section.',
    defaultProps: {
      kicker: 'Pourquoi nous',
      title: 'Tout ce qu’il faut, au bon prix.',
      subtitle:
        'Une équipe basée à Alger, des produits authentiques, et un SAV qui répond.',
      align: 'center',
    },
    defaultStyle: { paddingY: 48, paddingX: 24, maxWidth: 760 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'subtitle', label: 'Sous-titre', type: 'textarea' },
      {
        key: 'align',
        label: 'Alignement',
        type: 'select',
        options: [
          { label: 'Gauche', value: 'left' },
          { label: 'Centré', value: 'center' },
        ],
      },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'team',
    label: 'Équipe',
    category: 'Sections',
    icon: 'Users',
    description: 'Grille de membres d’équipe : photo, nom, rôle, bio.',
    defaultProps: {
      kicker: 'L’équipe',
      title: 'Ceux qui rendent ça possible',
      columns: 3,
      items: [
        { name: 'Yacine M.', role: 'Fondateur', bio: 'Tech, sourcing, négo avec les marques.', image: '' },
        { name: 'Sara B.',   role: 'Commerce', bio: 'Conseil aux pros, devis sur mesure.',    image: '' },
        { name: 'Amine R.',  role: 'Atelier',  bio: 'Montages PC, SAV, garanties.',           image: '' },
      ],
    },
    defaultStyle: { paddingY: 72, paddingX: 24 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'columns',
        label: 'Colonnes',
        type: 'select',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      {
        key: 'items',
        label: 'Membres',
        type: 'list',
        addLabel: 'Ajouter un membre',
        itemFields: [
          { key: 'image', label: 'Photo', type: 'image' },
          { key: 'name', label: 'Nom', type: 'text' },
          { key: 'role', label: 'Rôle', type: 'text' },
          { key: 'bio', label: 'Bio courte', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true },
  },
  {
    type: 'tabs',
    label: 'Onglets',
    category: 'Sections',
    icon: 'PanelTopOpen',
    description: 'Barre d’onglets avec contenu propre à chaque onglet.',
    defaultProps: {
      kicker: 'En détail',
      items: [
        { label: 'Caractéristiques', body: 'Décrivez les points forts de cet onglet.' },
        { label: 'Compatibilité', body: 'Listez les modèles supportés ou les prérequis.' },
        { label: 'Livraison & garantie', body: 'Délais, frais et SAV.' },
      ],
    },
    defaultStyle: { paddingY: 56, paddingX: 24, maxWidth: 980 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      {
        key: 'items',
        label: 'Onglets',
        type: 'list',
        addLabel: 'Ajouter un onglet',
        itemFields: [
          { key: 'label', label: 'Libellé', type: 'text' },
          { key: 'body', label: 'Contenu', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'steps',
    label: 'Étapes',
    category: 'Sections',
    icon: 'ListOrdered',
    description: 'Étapes numérotées (commande, montage, livraison…).',
    defaultProps: {
      kicker: 'Comment ça marche',
      title: 'Trois étapes simples',
      orientation: 'horizontal',
      items: [
        { title: 'Choisissez',   text: 'Parcourez le catalogue et ajoutez au panier.' },
        { title: 'Confirmez',    text: 'Validez la commande sur WhatsApp ou en ligne.' },
        { title: 'Recevez',      text: 'Livraison en Algérie ou retrait en showroom.' },
      ],
    },
    defaultStyle: { paddingY: 64, paddingX: 24, maxWidth: 1100 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'orientation',
        label: 'Orientation',
        type: 'select',
        options: [
          { label: 'Horizontale', value: 'horizontal' },
          { label: 'Verticale', value: 'vertical' },
        ],
      },
      {
        key: 'items',
        label: 'Étapes',
        type: 'list',
        addLabel: 'Ajouter une étape',
        itemFields: [
          { key: 'title', label: 'Titre', type: 'text' },
          { key: 'text', label: 'Description', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'timeline',
    label: 'Chronologie',
    category: 'Sections',
    icon: 'CalendarClock',
    description: 'Une chronologie verticale d’événements datés.',
    defaultProps: {
      kicker: 'Notre histoire',
      title: 'Quelques étapes clés',
      items: [
        { date: '2018', title: 'Ouverture du showroom', text: 'À Alger, autour de l’assemblage PC.' },
        { date: '2020', title: 'Catalogue en ligne',    text: 'Premier site marchand.' },
        { date: '2024', title: '393 produits',           text: '21 marques distribuées, 20 catégories.' },
      ],
    },
    defaultStyle: { paddingY: 64, paddingX: 24, maxWidth: 820 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Événements',
        type: 'list',
        addLabel: 'Ajouter un événement',
        itemFields: [
          { key: 'date', label: 'Date', type: 'text' },
          { key: 'title', label: 'Titre', type: 'text' },
          { key: 'text', label: 'Description', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'carousel',
    label: 'Carrousel',
    category: 'Médias',
    icon: 'GalleryHorizontal',
    description: 'Slider d’images/contenus à défilement horizontal natif.',
    defaultProps: {
      items: [
        { image: '/placeholder-product.png', caption: 'Slide #1' },
        { image: '/placeholder-product.png', caption: 'Slide #2' },
        { image: '/placeholder-product.png', caption: 'Slide #3' },
      ],
      ratio: '16/9',
      showDots: true,
    },
    defaultStyle: { paddingY: 32, paddingX: 24, radius: 14 },
    fields: [
      {
        key: 'ratio',
        label: 'Ratio',
        type: 'select',
        options: [
          { label: '16 / 9', value: '16/9' },
          { label: '4 / 3', value: '4/3' },
          { label: '1 / 1', value: '1/1' },
          { label: '3 / 4', value: '3/4' },
        ],
      },
      { key: 'showDots', label: 'Afficher les puces', type: 'toggle' },
      {
        key: 'items',
        label: 'Slides',
        type: 'list',
        addLabel: 'Ajouter une slide',
        itemFields: [
          { key: 'image', label: 'Image', type: 'image' },
          { key: 'caption', label: 'Légende', type: 'text' },
          { key: 'href', label: 'Lien (facultatif)', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true, border: true },
  },
  {
    type: 'banner',
    label: 'Bannière (info)',
    category: 'Sections',
    icon: 'Megaphone',
    description: 'Bandeau fin d’annonce — promo, alerte, info.',
    defaultProps: {
      tone: 'info',
      text: 'Livraison gratuite à partir de 30 000 DA — partout en Algérie.',
      ctaLabel: 'En savoir plus',
      ctaHref: '#',
    },
    defaultStyle: { paddingY: 12, paddingX: 24 },
    fields: [
      {
        key: 'tone',
        label: 'Ton',
        type: 'select',
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Succès', value: 'success' },
          { label: 'Promo', value: 'promo' },
          { label: 'Alerte', value: 'warn' },
        ],
      },
      { key: 'text', label: 'Texte', type: 'text' },
      { key: 'ctaLabel', label: 'Libellé du lien', type: 'text' },
      { key: 'ctaHref', label: 'URL du lien', type: 'text' },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'contactForm',
    label: 'Formulaire de contact',
    category: 'Sections',
    icon: 'Send',
    description: 'Formulaire prêt à brancher : nom, email, téléphone, sujet, message.',
    defaultProps: {
      kicker: 'Contact',
      title: 'Parlons de votre projet',
      action: '/api/inquiry',
      method: 'POST',
      nameLabel: 'Nom complet',
      emailLabel: 'E-mail',
      phoneLabel: 'Téléphone',
      subjectLabel: 'Sujet',
      messageLabel: 'Votre message',
      submitLabel: 'Envoyer →',
      consent:
        'En envoyant ce formulaire, vous acceptez d’être contacté par D-Tech.',
    },
    defaultStyle: { paddingY: 72, paddingX: 24, maxWidth: 720 },
    fields: [
      { key: 'kicker', label: 'Sur-titre', type: 'text' },
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'action', label: 'Action (URL)', type: 'text', placeholder: '/api/inquiry' },
      {
        key: 'method',
        label: 'Méthode',
        type: 'select',
        options: [
          { label: 'POST', value: 'POST' },
          { label: 'GET', value: 'GET' },
        ],
      },
      { key: 'nameLabel', label: 'Libellé Nom', type: 'text' },
      { key: 'emailLabel', label: 'Libellé E-mail', type: 'text' },
      { key: 'phoneLabel', label: 'Libellé Téléphone', type: 'text' },
      { key: 'subjectLabel', label: 'Libellé Sujet', type: 'text' },
      { key: 'messageLabel', label: 'Libellé Message', type: 'text' },
      { key: 'submitLabel', label: 'Libellé du bouton', type: 'text' },
      { key: 'consent', label: 'Mention de consentement', type: 'textarea' },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'socialLinks',
    label: 'Réseaux sociaux',
    category: 'Sections',
    icon: 'Share2',
    description: 'Rangée d’icônes / liens vers vos réseaux sociaux.',
    defaultProps: {
      title: 'Suivez-nous',
      items: [
        { network: 'facebook', handle: 'd.tech.algerie', href: 'https://facebook.com/' },
        { network: 'instagram', handle: '@d_tech.dz', href: 'https://instagram.com/' },
        { network: 'whatsapp', handle: '+213 560 99 05 06', href: 'https://wa.me/213560990506' },
      ],
    },
    defaultStyle: { paddingY: 32, paddingX: 24, textAlign: 'center' },
    fields: [
      { key: 'title', label: 'Titre', type: 'text' },
      {
        key: 'items',
        label: 'Comptes',
        type: 'list',
        addLabel: 'Ajouter un compte',
        itemFields: [
          {
            key: 'network',
            label: 'Réseau',
            type: 'select',
            options: ['facebook','instagram','whatsapp','linkedin','x','youtube','tiktok','mail','phone'].map((v) => ({ label: v, value: v })),
          },
          { key: 'handle', label: 'Pseudo / numéro', type: 'text' },
          { key: 'href', label: 'URL', type: 'text' },
        ],
      },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'buttonGroup',
    label: 'Groupe de boutons',
    category: 'Texte',
    icon: 'MoveHorizontal',
    description: 'Une rangée de 1 à 4 boutons — utile sous un titre.',
    defaultProps: {
      align: 'left',
      items: [
        { label: 'Voir le catalogue', href: '/products', variant: 'primary' },
        { label: 'Nous contacter', href: '/inquiry', variant: 'ghost' },
      ],
    },
    defaultStyle: { paddingY: 16, paddingX: 0 },
    fields: [
      {
        key: 'align',
        label: 'Alignement',
        type: 'select',
        options: [
          { label: 'Gauche', value: 'left' },
          { label: 'Centré', value: 'center' },
          { label: 'Droite', value: 'right' },
        ],
      },
      {
        key: 'items',
        label: 'Boutons',
        type: 'list',
        addLabel: 'Ajouter un bouton',
        itemFields: [
          { key: 'label', label: 'Libellé', type: 'text' },
          { key: 'href', label: 'Lien', type: 'text' },
          {
            key: 'variant',
            label: 'Style',
            type: 'select',
            options: [
              { label: 'Plein', value: 'primary' },
              { label: 'Contour', value: 'ghost' },
              { label: 'Lien', value: 'link' },
            ],
          },
        ],
      },
    ],
    style: { spacing: true, layout: true },
  },
  {
    type: 'accordion',
    label: 'Accordéon',
    category: 'Sections',
    icon: 'ChevronsUpDown',
    description: 'Panneaux repliables. Idéal pour des règles, options, fiches.',
    defaultProps: {
      items: [
        { title: 'Section 1', body: 'Le contenu apparaît au clic.' },
        { title: 'Section 2', body: 'Un panneau par sujet — gardez les textes courts.' },
      ],
      openFirst: true,
    },
    defaultStyle: { paddingY: 32, paddingX: 24, maxWidth: 820 },
    fields: [
      { key: 'openFirst', label: 'Ouvrir le premier panneau', type: 'toggle' },
      {
        key: 'items',
        label: 'Panneaux',
        type: 'list',
        addLabel: 'Ajouter un panneau',
        itemFields: [
          { key: 'title', label: 'Titre', type: 'text' },
          { key: 'body', label: 'Contenu', type: 'textarea' },
        ],
      },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'counter',
    label: 'Compteur',
    category: 'Texte',
    icon: 'Hash',
    description: 'Un seul gros chiffre avec libellé. (L’animation se déclenche au scroll côté site.)',
    defaultProps: {
      prefix: '',
      target: '393',
      suffix: '+',
      label: 'Produits en stock',
    },
    defaultStyle: { paddingY: 24, paddingX: 16, textAlign: 'center' },
    fields: [
      { key: 'prefix', label: 'Préfixe', type: 'text' },
      { key: 'target', label: 'Valeur cible', type: 'text' },
      { key: 'suffix', label: 'Suffixe', type: 'text', placeholder: '+, %, ans…' },
      { key: 'label', label: 'Libellé', type: 'text' },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'badge',
    label: 'Pastille (badge)',
    category: 'Texte',
    icon: 'Tag',
    description: 'Petite pastille colorée pour mettre en avant un mot.',
    defaultProps: { text: 'Nouveau', tone: 'mint' },
    defaultStyle: { paddingY: 4, paddingX: 10, radius: 999 },
    fields: [
      { key: 'text', label: 'Texte', type: 'text' },
      {
        key: 'tone',
        label: 'Couleur',
        type: 'select',
        options: [
          { label: 'Mint', value: 'mint' },
          { label: 'Ambre', value: 'amber' },
          { label: 'Bleu', value: 'blue' },
          { label: 'Rose', value: 'rose' },
          { label: 'Neutre', value: 'neutral' },
        ],
      },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'progress',
    label: 'Barre de progression',
    category: 'Texte',
    icon: 'BarChart',
    description: 'Barre de progression avec libellé et pourcentage.',
    defaultProps: { label: 'Stock disponible', value: 72 },
    defaultStyle: { paddingY: 12 },
    fields: [
      { key: 'label', label: 'Libellé', type: 'text' },
      { key: 'value', label: 'Valeur (%)', type: 'number' },
    ],
    style: { colors: true, spacing: true, typography: true },
  },
  {
    type: 'callout',
    label: 'Encadré (callout)',
    category: 'Texte',
    icon: 'Info',
    description: 'Encadré coloré pour une info, un avertissement ou un conseil.',
    defaultProps: {
      tone: 'info',
      title: 'Bon à savoir',
      text: 'Un message court qui attire l’œil sans crier.',
    },
    defaultStyle: { paddingY: 18, paddingX: 18, radius: 14 },
    fields: [
      {
        key: 'tone',
        label: 'Ton',
        type: 'select',
        options: [
          { label: 'Info (bleu)', value: 'info' },
          { label: 'Succès (vert)', value: 'success' },
          { label: 'Attention (ambre)', value: 'warn' },
          { label: 'Erreur (rouge)', value: 'error' },
        ],
      },
      { key: 'title', label: 'Titre', type: 'text' },
      { key: 'text', label: 'Texte', type: 'textarea' },
    ],
    style: { colors: true, spacing: true, typography: true, layout: true },
  },
  {
    type: 'code',
    label: 'Bloc de code',
    category: 'Avancé',
    icon: 'Code2',
    description: 'Bloc de code formaté en monospace (lisible, non exécuté).',
    defaultProps: {
      language: 'bash',
      code: 'pnpm install\npnpm dev',
    },
    defaultStyle: { paddingY: 16, paddingX: 18, radius: 12 },
    fields: [
      {
        key: 'language',
        label: 'Langage (étiquette)',
        type: 'text',
        placeholder: 'bash, tsx, json…',
      },
      { key: 'code', label: 'Code', type: 'textarea' },
    ],
    style: { colors: true, spacing: true, layout: true },
  },
  {
    type: 'embed',
    label: 'Iframe / embed',
    category: 'Avancé',
    icon: 'ExternalLink',
    description: 'iframe générique (CodePen, Twitter card, formulaire externe…).',
    defaultProps: { url: '', height: 480 },
    defaultStyle: { paddingY: 16, radius: 12 },
    fields: [
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://...' },
      { key: 'height', label: 'Hauteur (px)', type: 'number' },
    ],
    style: { spacing: true, border: true, layout: true },
  },

  // ────────────────────────── Avancé ──────────────────────────
  {
    type: 'html',
    label: 'HTML libre',
    category: 'Avancé',
    icon: 'Code',
    description: 'Insérez du HTML brut (avancé).',
    defaultProps: {
      html: '<div style="padding:24px;text-align:center">Votre <strong>HTML</strong> ici</div>',
    },
    defaultStyle: {},
    fields: [{ key: 'html', label: 'Code HTML', type: 'textarea' }],
    style: { spacing: true, colors: true },
  },
  {
    type: 'map',
    label: 'Carte (Maps)',
    category: 'Avancé',
    icon: 'Map',
    defaultProps: {
      query: 'Alger, Algérie',
      height: 360,
    },
    defaultStyle: { radius: 16 },
    fields: [
      { key: 'query', label: 'Adresse / lieu', type: 'text' },
      { key: 'height', label: 'Hauteur (px)', type: 'number' },
    ],
    style: { spacing: true, border: true },
  },
]

export const BLOCK_MAP: Record<string, BlockDef> = Object.fromEntries(
  BLOCKS.map((b) => [b.type, b])
)

export function getDef(type: string): BlockDef | undefined {
  return BLOCK_MAP[type]
}

/** Build a fresh block instance from its definition. */
export function createBlock(type: string): Block {
  const def = BLOCK_MAP[type]
  if (!def) throw new Error(`Unknown block type: ${type}`)
  const block: Block = {
    id: uid(),
    type,
    props: clone(def.defaultProps),
    style: clone(def.defaultStyle ?? {}) as BlockStyle,
  }
  if (def.isContainer) block.children = []
  return block
}


/** Short "how to use" notes shown in the palette help card + guide. */
export const HOWTO: Record<string, string> = {
  section: 'Glissez d’autres blocs à l’intérieur pour les regrouper en bande pleine largeur.',
  columns: 'Réglez 2 à 4 colonnes, puis déposez un bloc dans chaque colonne.',
  card: 'Un conteneur en verre : déposez du texte, un bouton ou une image dedans.',
  spacer: 'Ajoute du vide vertical entre deux blocs. Réglez sa hauteur.',
  divider: 'Une fine ligne de séparation entre deux sections.',
  eyebrow: 'Petit sur-titre en mono au-dessus d’un grand titre.',
  heading: 'Cliquez sur le titre pour le réécrire directement sur la page.',
  paragraph: 'Cliquez et tapez. Idéal pour une description ou un paragraphe.',
  list: 'Ajoutez des points dans les réglages ; basculez en liste numérotée.',
  quote: 'Mettez en avant un avis client ou une citation.',
  button: 'Un bouton d’action. Définissez le libellé, le lien et le style.',
  image: 'Collez une URL d’image et choisissez le ratio et l’ajustement.',
  gallery: 'Une grille d’images ; ajoutez-les dans les réglages.',
  video: 'Collez un lien YouTube, Vimeo ou MP4 ; il s’intègre automatiquement.',
  icon: 'Choisissez une icône et sa taille pour illustrer une idée.',
  logoCloud: 'Une rangée de noms de marques partenaires.',
  navbar: 'L’en-tête du site : marque, liens et bouton. Placez-le tout en haut.',
  hero: 'La grande section d’accueil : sur-titre, titre, sous-titre, boutons et stats.',
  heroSimple: 'Une accroche centrée, parfaite pour une landing page.',
  featureGrid: 'Présente 2 à 4 atouts avec icône, titre et texte.',
  statsBand: 'Une bande de chiffres clés (produits, marques…).',
  stat: 'Un seul chiffre mis en avant avec son libellé.',
  ctaBanner: 'Une bannière d’appel à l’action avec un bouton fort.',
  testimonials: 'Des cartes d’avis clients avec étoiles et auteur.',
  faq: 'Un accordéon de questions/réponses repliables.',
  pricing: 'Des cartes de tarifs ; cochez « mise en avant » pour l’offre vedette.',
  newsletter: 'Un bloc d’inscription e-mail.',
  contactBand: 'Téléphone, adresse et bouton WhatsApp.',
  imageText: 'Une image à côté d’un texte ; choisissez le côté de l’image.',
  footer: 'Le pied de page : marque, colonnes de liens et mention. Placez-le en bas.',
  productGrid: 'Une grille de produits (image, marque, prix, note).',
  categoryRail: 'Une rangée de cartes de catégories.',
  brandRail: 'Une rangée de pastilles de marques.',
  html: 'Insérez du code HTML brut (avancé).',
  map: 'Affiche une carte Google Maps centrée sur une adresse.',
  // ── v2 additions ──────────────────────────────────────────────
  heroImage: 'Hero avec une image plein-cadre en arrière-plan et un voile sombre réglable.',
  heroVideo: 'Hero avec une vidéo en boucle en fond ; supporte YouTube, Vimeo, et MP4.',
  heroSplit: 'Deux colonnes — copy à gauche, image à droite (ou inverse).',
  sectionHeader: 'Sur-titre + titre + sous-titre, pré-composés pour introduire une section.',
  team: 'Une grille de membres d’équipe : photo, nom, rôle, bio courte.',
  tabs: 'Plusieurs onglets ; le contenu visible change au clic.',
  steps: 'Étapes numérotées — horizontales ou verticales.',
  timeline: 'Une frise verticale avec date, titre, description.',
  carousel: 'Un slider d’images / contenus à défilement horizontal natif.',
  banner: 'Bandeau d’annonce (info / succès / promo / alerte) — pratique tout en haut de page.',
  contactForm: 'Formulaire prêt à brancher (nom, e-mail, téléphone, sujet, message).',
  socialLinks: 'Rangée d’icônes vers vos réseaux sociaux et autres canaux.',
  buttonGroup: 'Plusieurs boutons côte à côte — primaire + contour + lien.',
  accordion: 'Panneaux repliables (différent de la FAQ : structure générique).',
  counter: 'Un grand chiffre cible avec libellé. L’animation se déclenche au scroll.',
  badge: 'Petite pastille colorée pour souligner un mot (« Nouveau », « Promo »).',
  progress: 'Barre de progression avec libellé et pourcentage.',
  callout: 'Encadré coloré pour une info, une alerte ou un conseil.',
  code: 'Bloc de code formaté en monospace (lisible — non exécuté).',
  embed: 'iframe libre : CodePen, formulaire externe, widget tiers…',
}

BLOCKS.forEach((b) => {
  b.howto = HOWTO[b.type]
})

export const CATEGORIES: BlockDef['category'][] = [
  'Sections',
  'Texte',
  'Médias',
  'Commerce',
  'Layout',
  'Avancé',
]
