/**
 * Real D-Tech Algérie catalogue metadata: 21 brands, 20 categories.
 * Product rows come from catalogue.json (parsed from d-tech-catalogue-produits.md).
 */

export interface BrandMeta {
  slug: string
  name: string
  statement: string
  statementFr: string
  description: string
  descriptionFr: string
  sortOrder: number
}

export const brandMeta: BrandMeta[] = [
  { slug: 'hp', name: 'HP', sortOrder: 1,
    statement: 'Hardware that earns its place on the desk.',
    statementFr: 'Du matériel qui mérite sa place sur le bureau.',
    description: 'Laptops, desktops, monitors and printers — HP covers the complete professional workstation, from the OMEN gaming flagship to the EliteBook business range.',
    descriptionFr: "Portables, PC de bureau, écrans et imprimantes — HP couvre le poste de travail complet, du fleuron gaming OMEN à la gamme professionnelle EliteBook." },
  { slug: 'dell', name: 'Dell', sortOrder: 2,
    statement: 'Built for the people whose work makes other work possible.',
    statementFr: 'Conçu pour ceux dont le travail rend le travail des autres possible.',
    description: 'XPS, Latitude, Vostro, OptiPlex and the monitors to match: the professional spine of the catalogue, engineered without flourish.',
    descriptionFr: "XPS, Latitude, Vostro, OptiPlex et les écrans assortis : la colonne vertébrale professionnelle du catalogue, conçue sans fioritures." },
  { slug: 'lenovo', name: 'Lenovo', sortOrder: 3,
    statement: 'From ThinkPad keyboards to complete workstations.',
    statementFr: 'Du clavier ThinkPad au poste de travail complet.',
    description: 'ThinkPad, ThinkBook, IdeaPad, LOQ and ThinkCentre: Lenovo covers study, business and play with its legendary reliability.',
    descriptionFr: 'ThinkPad, ThinkBook, IdeaPad, LOQ et ThinkCentre : Lenovo couvre les études, le travail et le jeu avec sa fiabilité légendaire.' },
  { slug: 'asus', name: 'ASUS', sortOrder: 4,
    statement: 'Engineering for the people who care about the inside of the machine.',
    statementFr: "De l'ingénierie pour ceux qui s'intéressent à l'intérieur de la machine.",
    description: 'The biggest line in the catalogue: motherboards, graphics cards, routers, gaming gear and cooling — ASUS and ROG/TUF cover the whole build.',
    descriptionFr: 'La plus grande gamme du catalogue : cartes mères, cartes graphiques, routeurs, périphériques gaming et refroidissement — ASUS et ROG/TUF couvrent toute la machine.' },
  { slug: 'tp-link', name: 'TP-Link', sortOrder: 5,
    statement: 'Networks that disappear, then deliver.',
    statementFr: 'Des réseaux qui disparaissent, puis qui livrent.',
    description: 'Routers, mesh systems, managed switches, access points and adapters — the complete networking layer, from the studio to the enterprise floor.',
    descriptionFr: "Routeurs, systèmes mesh, switchs administrables, points d'accès et adaptateurs — la couche réseau complète, du studio au plateau d'entreprise." },
  { slug: 'epson', name: 'Epson', sortOrder: 6,
    statement: 'The ink tank that changed the economics of the page.',
    statementFr: "Le réservoir d'encre qui a changé l'économie de la page.",
    description: 'EcoTank multifunctions, WorkForce professionals, scanners, projectors and original inks: Epson owns the document chain.',
    descriptionFr: "Multifonctions EcoTank, gammes professionnelles WorkForce, scanners, vidéoprojecteurs et encres d'origine : Epson maîtrise toute la chaîne du document." },
  { slug: 'canon', name: 'Canon', sortOrder: 7,
    statement: 'Printing, taken seriously since 1937.',
    statementFr: "L'impression, prise au sérieux depuis 1937.",
    description: 'i-SENSYS lasers, MegaTank PIXMA, imageRUNNER copiers, CanoScan scanners and original toners — from the single desk to the workgroup.',
    descriptionFr: 'Lasers i-SENSYS, MégaTank PIXMA, copieurs imageRUNNER, scanners CanoScan et toners d’origine — du bureau individuel au groupe de travail.' },
  { slug: 'msi', name: 'MSI', sortOrder: 8,
    statement: 'Monitors tuned for work and for war.',
    statementFr: 'Des écrans réglés pour le travail comme pour le jeu.',
    description: 'PRO series monitors for long office days, MPG OLED panels for competitive play.',
    descriptionFr: 'Écrans PRO pour les longues journées de bureau, dalles MPG OLED pour le jeu compétitif.' },
  { slug: 'apc', name: 'APC', sortOrder: 9,
    statement: 'The reference in power protection.',
    statementFr: 'La référence de la protection électrique.',
    description: 'Back-UPS and Smart-UPS units that keep desks, servers and networks alive through every cut.',
    descriptionFr: 'Onduleurs Back-UPS et Smart-UPS qui maintiennent postes, serveurs et réseaux en vie à chaque coupure.' },
  { slug: 'unomat', name: 'Unomat', sortOrder: 10,
    statement: 'Dependable power protection, sized for every budget.',
    statementFr: 'Une protection électrique fiable, adaptée à chaque budget.',
    description: 'From 650 VA desk units to 3 kVA rackmount UPS — straightforward power backup for homes and businesses.',
    descriptionFr: "Du modèle 650 VA de bureau à l'onduleur rack 3 kVA — une protection simple et efficace pour la maison et l'entreprise." },
  { slug: 'gamemax', name: 'GameMax', sortOrder: 11,
    statement: 'The case, the power, the glow.',
    statementFr: 'Le boîtier, la puissance, la lumière.',
    description: 'PC cases, power supplies, fans and gaming accessories with ARGB attitude at honest prices.',
    descriptionFr: 'Boîtiers PC, alimentations, ventilateurs et accessoires gaming avec attitude ARGB à prix honnêtes.' },
  { slug: 'ink-master', name: 'Ink Master', sortOrder: 12,
    statement: 'Compatible consumables, original results.',
    statementFr: 'Consommables compatibles, résultats originaux.',
    description: 'Compatible toners for Kyocera, Canon, HP and Brother fleets — the smart cost-per-page play.',
    descriptionFr: 'Toners compatibles pour parcs Kyocera, Canon, HP et Brother — le bon calcul du coût par page.' },
  { slug: 'hiksemi', name: 'Hiksemi', sortOrder: 13,
    statement: 'Storage that keeps up.',
    statementFr: 'Du stockage qui suit la cadence.',
    description: 'SATA and NVMe SSDs plus portable drives, from 256 GB to 2 TB.',
    descriptionFr: 'SSD SATA et NVMe et disques portables, de 256 Go à 2 To.' },
  { slug: 'dtech', name: 'D-Tech', sortOrder: 14,
    statement: 'The house line — built for Algeria.',
    statementFr: 'La gamme maison — pensée pour l’Algérie.',
    description: 'ProTab tablets and DP power banks designed and priced for the local market.',
    descriptionFr: 'Tablettes ProTab et power banks DP, conçues et tarifées pour le marché local.' },
  { slug: 'intel', name: 'Intel', sortOrder: 15,
    statement: 'The silicon standard.',
    statementFr: 'Le standard du silicium.',
    description: 'Core processors for every build the catalogue assembles.',
    descriptionFr: 'Processeurs Core pour toutes les configurations que le catalogue assemble.' },
  { slug: 'amd', name: 'AMD', sortOrder: 16,
    statement: 'Performance per dinar.',
    statementFr: 'La performance par dinar.',
    description: 'Ryzen processors and Radeon graphics for builders who count cores and dinars.',
    descriptionFr: 'Processeurs Ryzen et cartes Radeon pour ceux qui comptent les cœurs et les dinars.' },
  { slug: 'tcl', name: 'TCL', sortOrder: 17,
    statement: 'Internet, wherever there is signal.',
    statementFr: 'Internet, partout où il y a du signal.',
    description: 'LinkHub 4G routers and LinkZone mobile hotspots — connectivity without the landline.',
    descriptionFr: 'Routeurs 4G LinkHub et hotspots LinkZone — la connectivité sans ligne fixe.' },
  { slug: 'mercusys', name: 'Mercusys', sortOrder: 18,
    statement: 'Simple networking, smart prices.',
    statementFr: 'Le réseau simple, au prix malin.',
    description: 'Entry networking gear by TP-Link’s sister brand.',
    descriptionFr: 'Équipement réseau d’entrée de gamme par la marque sœur de TP-Link.' },
  { slug: 'game-revolution', name: 'Game Revolution', sortOrder: 19,
    statement: 'Gaming monitors with mythological refresh rates.',
    statementFr: 'Des écrans gaming aux fréquences mythologiques.',
    description: 'Armaguedon, Apocalyps, Ragnarok: high-refresh gaming panels at accessible prices.',
    descriptionFr: 'Armaguedon, Apocalyps, Ragnarok : des dalles gaming haute fréquence à prix accessibles.' },
  { slug: 'reaction', name: 'Reaction', sortOrder: 20,
    statement: 'Monitors for every desk.',
    statementFr: 'Des écrans pour tous les bureaux.',
    description: 'Dependable office and gaming displays at entry prices.',
    descriptionFr: 'Des écrans bureautiques et gaming fiables, à prix d’entrée.' },
  { slug: 'aoc', name: 'AOC', sortOrder: 21,
    statement: 'Displays with a designer’s eye.',
    statementFr: 'Des écrans avec un œil de designer.',
    description: 'Monitors balancing image quality and price.',
    descriptionFr: 'Des moniteurs qui équilibrent qualité d’image et prix.' },
]

export interface CategoryMeta {
  slug: string
  name: string
  nameFr: string
  description: string
  descriptionFr: string
  sortOrder: number
}

export const categoryMeta: CategoryMeta[] = [
  { slug: 'laptops', name: 'Laptops', nameFr: 'Ordinateurs portables', sortOrder: 1,
    description: 'From student IdeaPads to OMEN gaming flagships and EliteBook ultraportables — 30 machines, sorted by intent.',
    descriptionFr: "De l'IdeaPad étudiant au fleuron gaming OMEN en passant par les ultraportables EliteBook — 30 machines, classées par usage." },
  { slug: 'desktops', name: 'Desktops', nameFr: 'Ordinateurs de bureau', sortOrder: 2,
    description: 'OptiPlex, Pro Tower and ThinkCentre desktops, from micro form factor to full tower.',
    descriptionFr: 'PC de bureau OptiPlex, Pro Tower et ThinkCentre, du format micro à la grande tour.' },
  { slug: 'all-in-one', name: 'All-in-One', nameFr: 'Tout-en-un', sortOrder: 3,
    description: 'The complete workstation in a single chassis — fewer cables, more desk.',
    descriptionFr: 'Le poste de travail complet dans un seul châssis — moins de câbles, plus de bureau.' },
  { slug: 'monitors', name: 'Monitors', nameFr: 'Écrans & moniteurs', sortOrder: 4,
    description: 'Fifty panels: 4K professional, USB-C docking, OLED 360 Hz gaming and honest office screens.',
    descriptionFr: 'Cinquante dalles : 4K professionnel, USB-C, gaming OLED 360 Hz et écrans bureautiques honnêtes.' },
  { slug: 'tablets', name: 'Tablets', nameFr: 'Tablettes', sortOrder: 5,
    description: 'Android tablets for the family, the field and the classroom.',
    descriptionFr: 'Tablettes Android pour la famille, le terrain et la classe.' },
  { slug: 'printers', name: 'Printers & Copiers', nameFr: 'Imprimantes & copieurs', sortOrder: 6,
    description: 'EcoTank, MegaTank, i-SENSYS lasers and imageRUNNER copiers — every printing volume covered.',
    descriptionFr: 'EcoTank, MégaTank, lasers i-SENSYS et copieurs imageRUNNER — tous les volumes d’impression couverts.' },
  { slug: 'scanners', name: 'Scanners', nameFr: 'Scanners', sortOrder: 7,
    description: 'Flatbed and sheet-fed document scanners, from the drawer-sized LiDE to production machines.',
    descriptionFr: 'Scanners à plat et à défilement, du LiDE format tiroir aux machines de production.' },
  { slug: 'projectors', name: 'Projectors', nameFr: 'Vidéoprojecteurs', sortOrder: 8,
    description: 'Epson projection for the meeting room and the classroom.',
    descriptionFr: 'La projection Epson pour la salle de réunion et la salle de classe.' },
  { slug: 'consumables', name: 'Toners & Inks', nameFr: 'Consommables (toners & encres)', sortOrder: 9,
    description: 'Original Canon and Epson supplies plus Ink Master compatibles — the cost per page, managed.',
    descriptionFr: 'Consommables d’origine Canon et Epson et compatibles Ink Master — le coût par page, maîtrisé.' },
  { slug: 'storage', name: 'Storage (SSD)', nameFr: 'Stockage (SSD)', sortOrder: 10,
    description: 'SATA and NVMe SSDs from 256 GB to 2 TB, internal and portable.',
    descriptionFr: 'SSD SATA et NVMe de 256 Go à 2 To, internes et portables.' },
  { slug: 'motherboards', name: 'Motherboards', nameFr: 'Cartes mères', sortOrder: 11,
    description: 'Twenty-nine ASUS boards: PRIME, TUF and ROG, for Intel and AMD platforms.',
    descriptionFr: 'Vingt-neuf cartes ASUS : PRIME, TUF et ROG, pour plateformes Intel et AMD.' },
  { slug: 'graphics-cards', name: 'Graphics Cards', nameFr: 'Cartes graphiques', sortOrder: 12,
    description: 'GeForce and Radeon boards, from display output to ray-traced flagships.',
    descriptionFr: 'Cartes GeForce et Radeon, de la simple sortie vidéo aux fleurons ray tracing.' },
  { slug: 'processors', name: 'Processors', nameFr: 'Processeurs', sortOrder: 13,
    description: 'Intel Core and AMD Ryzen chips for every build on the bench.',
    descriptionFr: 'Puces Intel Core et AMD Ryzen pour toutes les configurations.' },
  { slug: 'power-supplies', name: 'Power Supplies', nameFr: 'Alimentations (PSU)', sortOrder: 14,
    description: 'Certified PSUs that treat your components like they cost money — because they did.',
    descriptionFr: 'Alimentations certifiées qui traitent vos composants comme s’ils avaient coûté cher — parce que c’est le cas.' },
  { slug: 'pc-cases', name: 'PC Cases', nameFr: 'Boîtiers PC', sortOrder: 15,
    description: 'Towers with tempered glass, ARGB and airflow to spare.',
    descriptionFr: 'Des tours avec verre trempé, ARGB et flux d’air à revendre.' },
  { slug: 'cooling', name: 'Cooling', nameFr: 'Refroidissement', sortOrder: 16,
    description: 'ARGB fans and all-in-one watercooling, from silent office builds to 420 mm radiators.',
    descriptionFr: 'Ventilateurs ARGB et watercooling tout-en-un, du PC silencieux au radiateur 420 mm.' },
  { slug: 'ups', name: 'UPS', nameFr: 'Onduleurs (UPS)', sortOrder: 17,
    description: 'Twenty-six APC and Unomat units, from 650 VA desk guards to 3 kVA rackmounts.',
    descriptionFr: 'Vingt-six onduleurs APC et Unomat, du 650 VA de bureau au rack 3 kVA.' },
  { slug: 'networking', name: 'Networking', nameFr: 'Réseau & connectivité', sortOrder: 18,
    description: 'Fifty-seven routers, switches, mesh systems, access points and adapters — the deepest section of the catalogue.',
    descriptionFr: "Cinquante-sept routeurs, switchs, systèmes mesh, points d'accès et adaptateurs — la section la plus profonde du catalogue." },
  { slug: 'gaming', name: 'Gaming Gear', nameFr: 'Périphériques gaming', sortOrder: 19,
    description: 'ROG and TUF keyboards, mice and headsets, plus GameMax accessories.',
    descriptionFr: 'Claviers, souris et casques ROG et TUF, plus les accessoires GameMax.' },
  { slug: 'power-banks', name: 'Power Banks', nameFr: 'Batteries externes', sortOrder: 20,
    description: 'D-Tech DP power banks from 10,000 to 40,000 mAh.',
    descriptionFr: 'Power banks D-Tech DP de 10 000 à 40 000 mAh.' },
]
