'use client'

/**
 * ÉDITEUR — les icônes des sections.
 *
 * Le registre nomme son icône par une chaîne (`icon: 'Megaphone'`) pour rester
 * un module de données. La correspondance vit ici, en import statique : un
 * `import()` dynamique par nom empêcherait le regroupement des modules et
 * ferait clignoter la bibliothèque au premier affichage.
 */

import {
  AlignLeft,
  BarChart3,
  BookOpen,
  Building2,
  Code,
  Columns2,
  Columns3,
  CreditCard,
  ExternalLink,
  FileQuestion,
  FileText,
  Flag,
  Gamepad2,
  Grid2x2,
  Grid3x3,
  Hash,
  Heading1,
  Heading2,
  Heart,
  HelpCircle,
  Image as ImageIcon,
  Images,
  Info,
  Layers,
  LayoutGrid,
  LayoutList,
  ListOrdered,
  ListTree,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Milestone,
  Minus,
  MonitorSmartphone,
  MoreHorizontal,
  MousePointerClick,
  MoveVertical,
  Network,
  Package,
  PanelTop,
  Phone,
  Play,
  Quote,
  Repeat,
  Scale,
  Search,
  ShieldCheck,
  Sparkle,
  Sparkles,
  Square,
  Tag,
  Type,
  Users,
  Wrench,
} from 'lucide-react'

const MAP: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  AlignLeft,
  BarChart3,
  BookOpen,
  Building2,
  Code,
  Columns2,
  Columns3,
  CreditCard,
  ExternalLink,
  FileQuestion,
  FileText,
  Flag,
  Gamepad2,
  Grid2x2,
  Grid3x3,
  Hash,
  Heading1,
  Heading2,
  Heart,
  HelpCircle,
  Image: ImageIcon,
  Images,
  Info,
  Layers,
  LayoutGrid,
  LayoutList,
  ListOrdered,
  ListTree,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Milestone,
  Minus,
  MonitorSmartphone,
  MoreHorizontal,
  MousePointerClick,
  MoveVertical,
  Network,
  Package,
  PanelTop,
  Phone,
  Play,
  Quote,
  Repeat,
  Scale,
  Search,
  ShieldCheck,
  Sparkle,
  Sparkles,
  Tag,
  Type,
  Users,
  Wrench,
}

export function EdIcon({ name, size = 15 }: { name?: string; size?: number }) {
  const Cmp = (name && MAP[name]) || Square
  return <Cmp size={size} />
}
